In [1]:
import sys
import importlib
from types import SimpleNamespace
import matplotlib.pyplot as plt
from tqdm import tqdm
from scipy.special import softmax
from joblib import Parallel, delayed
# import seaborn as sns
import scipy as sp

import warnings
warnings.filterwarnings("ignore")

sys.path.append("/home/hhl/바탕화면/dacon/dacon21/model/using_cofing")
# sys.argv = ['--config', 'config1_try']
sys.argv = ['--config', 'config1']

from models import *
from loss import *
from run import *
from utils import *

Using config file config1


In [2]:
class config1:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    channels_last=False
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b3_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=12
    n_splits=5
    fold=0
    seed=1028
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config1/tf_efficientnet_b3_ns_best_fold_0.pth'

In [3]:
class config2:
    DEBUG=False
    num_workers=8
    gpus=0
    distributed_backend=None
    sync_batchnorm=True
    channels_last=False
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b4_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45
    arcface_m=0.4
    head='arc_margin'
    neck='option-D'
    pretrained_weights=None
    optim='sgd'
    batch_size=7
    n_splits = 5
    fold=0
    seed=794621
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config2/tf_efficientnet_b4_ns_best_fold_0.pth'

In [4]:
class config3:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b2_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=15
    n_splits=5
    fold=0
    seed=756
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config4/tf_efficientnet_b2_ns_best_fold_0.pth'

In [5]:
class config4:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b3_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=9
    n_splits=5
    fold=0
    seed=204
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config3/tf_efficientnet_b3_ns_best_fold_0.pth'

In [6]:
class config5:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b2_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=12
    n_splits=5
    fold=0
    seed=1214
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config5/tf_efficientnet_b2_ns_best_fold_0.pth'

In [2]:
class config6:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b1_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=9
    n_splits=5
    fold=0
    seed=9999
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config6/tf_efficientnet_b1_ns_best_fold_0.pth'

In [8]:
class config7:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b1_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=9
    n_splits=5
    fold=0
    seed=9999
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config7/tf_efficientnet_b1_ns_best_fold_0.pth'

In [9]:
class config8:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b1_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=9
    n_splits=5
    fold=0
    seed=9999
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config8/tf_efficientnet_b1_ns_best_fold_0.pth'

In [10]:
class config9:
    DEBUG=False
    num_workers=8
    gpus='0'
    distributed_backend=None
    sync_batchnorm=True
    gradient_accumulation_steps=4
    precision=16
    warmup_epo=1
    cosine_epo=19
    lr=0.002
    weight_decay=0.0001
    p_trainable=True
    crit='bce'
    backbone='tf_efficientnet_b1_ns'
    embedding_size=512
    pool='gem'
    arcface_s=45.0
    arcface_m=0.4
    neck='option-D'
    head='arc_margin'
    pretrained_weights=None
    optim='sgd'
    batch_size=9
    n_splits=5
    fold=0
    seed=9999
    device='cuda:0'
    out_dim=1049
    n_classes=1049
    class_weights='log'
    class_weights_norm='batch'
    normalization='imagenet'
    crop_size=448
    model='/home/hhl/바탕화면/dacon/dacon21/model/config9/tf_efficientnet_b1_ns_best_fold_0.pth'

In [11]:
class LMDataset(Dataset): 
    def __init__(self, csv): 
        self.csv = csv.filepath.values
    def __getitem__(self, index):
        img_path = self.csv[index]
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        img1 = val_aug1(image=img)['image'].astype(np.float32)
        img1 = self.normalize_img(img1)
        tensor1 = self.to_torch_tensor(img1)
        feature_dict1 = {'idx':torch.tensor(index).long(), 'input':tensor1}

        img2 = val_aug2(image=img)['image'].astype(np.float32)
        img2 = self.normalize_img(img2)
        tensor2 = self.to_torch_tensor(img2)
        feature_dict2 = {'idx':torch.tensor(index).long(), 'input':tensor2}

        img3 = val_aug3(image=img)['image'].astype(np.float32)
        img3 = self.normalize_img(img3)
        tensor3 = self.to_torch_tensor(img3)
        feature_dict3 = {'idx':torch.tensor(index).long(), 'input':tensor3}

        img4 = val_aug4(image=img)['image'].astype(np.float32)
        img4 = self.normalize_img(img4)
        tensor4 = self.to_torch_tensor(img4)
        feature_dict4 = {'idx':torch.tensor(index).long(), 'input':tensor4}

        img5 = val_aug4(image=img)['image'].astype(np.float32)
        img5 = self.normalize_img(img5)
        tensor5 = self.to_torch_tensor(img5)
        feature_dict5 = {'idx':torch.tensor(index).long(), 'input':tensor5}
        return feature_dict1, feature_dict2, feature_dict3, feature_dict4, feature_dict5

    def __len__(self): 
        return len(self.csv)
    def normalize_img(self,img):
        mean = np.array([123.675, 116.28 , 103.53 ], dtype=np.float32)
        std = np.array([58.395   , 57.120, 57.375 ], dtype=np.float32)
        img = img.astype(np.float32)
        img -= mean
        img *= np.reciprocal(std, dtype=np.float32)
        return img
    def to_torch_tensor(self,img):
        return torch.from_numpy(img.transpose((2, 0, 1)))

In [12]:
val_aug1 = A.Compose([ 
    A.LongestMaxSize(664,p=1),
    A.PadIfNeeded(664, 664, border_mode=cv2.BORDER_CONSTANT,p=1),
    A.CenterCrop(always_apply=False, p=1.0, height=config1.crop_size, width=config1.crop_size), 
    ], p=1.0
    )

val_aug2 = A.Compose([
        A.ImageCompression(quality_lower=99, quality_upper=100),    
        A.Resize(512, 512),
    ])

val_aug3 = A.Compose([
        A.ImageCompression(quality_lower=99, quality_upper=100),    
        A.Resize(448, 448),
    ])

val_aug4 = A.Compose([
        A.ImageCompression(quality_lower=99, quality_upper=100),    
        A.Resize(768, 768),
    ])

val_aug5 = A.Compose([
        A.ImageCompression(quality_lower=99, quality_upper=100),    
        A.Resize(484, 484),
    ])

In [13]:
def test(model, valid_loader):
    from tqdm import tqdm
    model.eval()
    val_outputs = []
    with torch.no_grad():
        for batch in tqdm(valid_loader):
            batch['input'] = batch['input'].to(args.device)

            output_dict = model(batch, get_embeddings=True)
            logits = output_dict['logits']
            embeddings = output_dict['embeddings']   

            output = dict({
                'idx':batch['idx'].detach().cpu().numpy().astype(int),
                'embeddings': embeddings.detach().cpu().numpy(),
                
            })
            val_outputs += [output] 
    return val_outputs

In [14]:
set_seed(0)
train = pd.read_csv('../data/public/train.csv')
train['filepath'] = [os.path.join('../data/train', str(lm_id), str(id)+'.JPG') for lm_id, id in zip(train['landmark_id'], train['id'])]
sub = pd.read_csv('../data/public/sample_submission.csv')
sub['filepath'] = [os.path.join('../data/public/test', id, folder+'.JPG') for id, folder in zip(sub['id'].apply(lambda x: x[0]), sub['id'])]

train_dataset = LMDataset(train)
train_loader = DataLoader(dataset=train_dataset, batch_size=36, num_workers=8, shuffle=False, pin_memory=True)

test_dataset = LMDataset(sub)
test_loader = DataLoader(dataset=test_dataset, batch_size=36, num_workers=8, shuffle=False, pin_memory=True)

In [15]:
model1 = Net(config1)
model2 = Net(config2)
model3 = Net(config3)
model4 = Net(config4)
model5 = Net(config5)
model6 = Net(config6)
model7 = Net(config7)
model8 = Net(config8)
model9 = Net(config9)

model1 = model1.to('cuda:0')
model2 = model2.to('cuda:0')
model3 = model3.to('cuda:0')
model4 = model4.to('cuda:0')
model5 = model5.to('cuda:0')
model6 = model6.to('cuda:0')
model7 = model7.to('cuda:0')
model8 = model8.to('cuda:0')
model9 = model9.to('cuda:0')

model1.load_state_dict(torch.load(config1.model))
model2.load_state_dict(torch.load(config2.model))
model3.load_state_dict(torch.load(config3.model))
model4.load_state_dict(torch.load(config4.model))
model5.load_state_dict(torch.load(config5.model))
model6.load_state_dict(torch.load(config6.model))
model7.load_state_dict(torch.load(config7.model))
model8.load_state_dict(torch.load(config8.model))
model9.load_state_dict(torch.load(config9.model))

<All keys matched successfully>

In [16]:
from tqdm import tqdm
CLS_TOP_K=5
TOP_K=5
model1.eval()
model2.eval()
model3.eval()
model4.eval()
model5.eval()
model6.eval()
model7.eval()
model8.eval()
model9.eval()

with torch.no_grad():
    feats = []
    for batch, batch2, batch3, batch4, batch5 in tqdm(train_loader):
        batch['input'] = batch['input'].to('cuda:0')
        batch2['input'] = batch2['input'].to('cuda:0')
        batch3['input'] = batch3['input'].to('cuda:0')
        batch4['input'] = batch4['input'].to('cuda:0')
        batch5['input'] = batch5['input'].to('cuda:0')
        
        output_dict1 = model1(batch, get_embeddings=True)
        output_dict2 = model2(batch2, get_embeddings=True)
        output_dict3 = model3(batch2, get_embeddings=True)
        output_dict4 = model4(batch3, get_embeddings=True)
        output_dict5 = model5(batch2, get_embeddings=True)
        output_dict6 = model6(batch2, get_embeddings=True)
        output_dict7 = model7(batch4, get_embeddings=True)
        output_dict8 = model8(batch3, get_embeddings=True)
        output_dict9 = model9(batch5, get_embeddings=True)
        
        feat = torch.cat([output_dict1['embeddings'], output_dict2['embeddings'], output_dict3['embeddings'],output_dict4['embeddings'], output_dict5['embeddings'], output_dict6['embeddings'], output_dict7['embeddings'], output_dict8['embeddings'], output_dict9['embeddings']], dim=1)
        feats.append(feat.detach().cpu())
    else:
        feats = torch.cat(feats)
        feats = feats.to('cuda:0')
        feats = F.normalize(feats)
        
    PRODS = []
    PREDS = []
    PRODS_M = []
    PREDS_M = []     
    
    for batch, batch2, batch3, batch4, batch5 in tqdm(test_loader):
        batch['input'] = batch['input'].to('cuda:0')
        batch2['input'] = batch2['input'].to('cuda:0')
        batch3['input'] = batch3['input'].to('cuda:0')
        batch4['input'] = batch4['input'].to('cuda:0')
        batch5['input'] = batch5['input'].to('cuda:0')
        

        output_dict = model1(batch,  get_embeddings=True) ; logits =  output_dict['logits'] ; embeddings1 = output_dict['embedding']
        output_dict = model2(batch2, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings2 = output_dict['embedding']
        output_dict = model3(batch2, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings3 = output_dict['embedding']
        output_dict = model4(batch3, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings4 = output_dict['embedding']
        output_dict = model5(batch2, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings5 = output_dict['embedding']
        output_dict = model6(batch2, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings6 = output_dict['embedding']
        output_dict = model7(batch4, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings7 = output_dict['embedding']
        output_dict = model8(batch3, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings8 = output_dict['embedding']
        output_dict = model9(batch5, get_embeddings=True) ; logits += output_dict['logits'] ; embeddings9 = output_dict['embedding']
        

        feat = torch.cat([embeddings1, embeddings2, embeddings3, embeddings4, embeddings5, embeddings6, embeddings7, embeddings8, embeddings9], dim=1)
        feat = F.normalize(feat)
        
        logits=logits/9
        
        (values, indices) = torch.topk(logits, CLS_TOP_K, dim=1)
        probs_m = values
        preds_m = indices  
        
        PRODS_M.append(probs_m.detach().cpu())
        PREDS_M.append(preds_m.detach().cpu())  
        
        distance = feat.mm(feats.t())
        (values, indices) = torch.topk(distance, TOP_K, dim=1)
        probs = values
        preds = indices
        PRODS.append(probs.detach().cpu())
        PREDS.append(preds.detach().cpu())
        
    PRODS = torch.cat(PRODS).numpy()
    PREDS = torch.cat(PREDS).numpy()
    PRODS_M = torch.cat(PRODS_M).numpy()
    PREDS_M = torch.cat(PREDS_M).numpy()

100%|██████████| 1055/1055 [31:24<00:00,  1.79s/it]


In [17]:
PRODS

array([[0.9681861 , 0.9588182 , 0.95706064, 0.95588136, 0.95040643],
       [0.96667993, 0.9472121 , 0.9447556 , 0.9408512 , 0.94078714],
       [0.9377258 , 0.912168  , 0.90437233, 0.88918334, 0.88405263],
       ...,
       [0.9671086 , 0.96655184, 0.9575849 , 0.9565214 , 0.94599533],
       [0.9174435 , 0.90726936, 0.90146875, 0.89430594, 0.89088726],
       [0.9650006 , 0.9605202 , 0.9572787 , 0.94926447, 0.94199556]],
      dtype=float32)

In [18]:
PREDS

array([[46165, 46223, 46177, 46178, 46214],
       [46212, 46166, 46164, 46178, 46193],
       [46179, 46204, 46238, 46212, 46206],
       ...,
       [87205, 87197, 87263, 87269, 87247],
       [87230, 87197, 87205, 87269, 87263],
       [87269, 87263, 87205, 87197, 87196]])

In [19]:
PRODS_M

array([[0.8262315 , 0.17035033, 0.16999641, 0.16363013, 0.16199456],
       [0.8278582 , 0.16406849, 0.1602645 , 0.15817578, 0.15451196],
       [0.79496634, 0.1899417 , 0.18392396, 0.17450395, 0.16595139],
       ...,
       [0.82473266, 0.24279721, 0.17697482, 0.1700898 , 0.16491812],
       [0.8146967 , 0.22368771, 0.16808186, 0.15954326, 0.15771452],
       [0.81549466, 0.2523113 , 0.16957906, 0.16657   , 0.16497181]],
      dtype=float32)

In [20]:
PREDS_M

array([[ 956,  547,  674,  524,  184],
       [ 956,  547,  524,  849, 1040],
       [ 956,  184,  557,  547,  496],
       ...,
       [ 901,  675,  555,   94,  655],
       [ 901,  675,  555,  613,   52],
       [ 901,  675,  325,  856,  555]])

In [21]:
np.save('ensembles/PRODS.npy', PRODS)
np.save('ensembles/PREDS.npy', PREDS)
np.save('ensembles/PREDS_M.npy', PREDS_M)
np.save('ensembles/PREDS_M.npy', PREDS_M)

In [22]:
landmark = train['landmark_id'].values
PREDS2 = landmark[PREDS]
# PREDS_M = np.vectorize(idx2landmark_id.get)(PREDS_M)

In [ ]:
with open(os.path.join(model_dir, 'idx2landmark_id.pkl'), 'rb') as fp:
    idx2landmark_id = pickle.load(fp)
    landmark_id2idx = {idx2landmark_id[idx]: idx for idx in idx2landmark_id.keys()}
    
pred_mask = pd.Series(df.landmark_id.unique()).map(landmark_id2idx).values

In [24]:
np.vectorize(idx2landmark_id.get)

In [25]:
PREDS2.min(), PREDS2.max(), PREDS_M.min(), PREDS_M.max()

(0, 1048, 0, 1048)

In [26]:
PREDS_M

array([[ 956,  547,  674,  524,  184],
       [ 956,  547,  524,  849, 1040],
       [ 956,  184,  557,  547,  496],
       ...,
       [ 901,  675,  555,   94,  655],
       [ 901,  675,  555,  613,   52],
       [ 901,  675,  325,  856,  555]])

In [58]:
PREDS2[:3,:]

array([[956, 956, 956],
       [956, 956, 956],
       [956, 956, 956]])

In [27]:
PREDS_M[:3,:]

array([[ 956,  547,  674,  524,  184],
       [ 956,  547,  524,  849, 1040],
       [ 956,  184,  557,  547,  496]])

In [28]:
PRODS[:3,:]

array([[0.9681861 , 0.9588182 , 0.95706064, 0.95588136, 0.95040643],
       [0.96667993, 0.9472121 , 0.9447556 , 0.9408512 , 0.94078714],
       [0.9377258 , 0.912168  , 0.90437233, 0.88918334, 0.88405263]],
      dtype=float32)

In [29]:
PRODS_M[:3,:]

array([[0.8262315 , 0.17035033, 0.16999641, 0.16363013, 0.16199456],
       [0.8278582 , 0.16406849, 0.1602645 , 0.15817578, 0.15451196],
       [0.79496634, 0.1899417 , 0.18392396, 0.17450395, 0.16595139]],
      dtype=float32)

In [30]:
PRODS_F = []
PREDS_F = []
for i in tqdm(range(PREDS2.shape[0])):
    tmp = {}
    classify_dict = {PREDS_M[i,j] : PRODS_M[i,j] for j in range(CLS_TOP_K)}
    for k in range(TOP_K):
        lid = PREDS2[i, k]
        tmp[lid] = tmp.get(lid, 0.) + float(PRODS[i, k]) ** 9 * classify_dict.get(lid,1e-8)**10
    pred, conf = max(tmp.items(), key=lambda x: x[1])
    PREDS_F.append(pred)
    PRODS_F.append(conf)

100%|██████████| 37964/37964 [00:00<00:00, 46493.55it/s]


In [31]:
sub['landmark_id']=PREDS_F
sub['conf']=PRODS_F

In [32]:
sub

id  landmark_id      conf                              filepath
0      xlf1tgh2ih          956  0.504824  ../data/public/test/x/xlf1tgh2ih.JPG
1      68a3ot4osk          956  0.469569  ../data/public/test/6/68a3ot4osk.JPG
2      si2lek4u0a          956  0.209661  ../data/public/test/s/si2lek4u0a.JPG
3      rmtqxhipnv          956  0.364817  ../data/public/test/r/rmtqxhipnv.JPG
4      2flmjdud0e          956  0.599650  ../data/public/test/2/2flmjdud0e.JPG
...           ...          ...       ...                                   ...
37959  8nlfrrdnwk          901  0.385468  ../data/public/test/8/8nlfrrdnwk.JPG
37960  k0w00aa3iy          901  0.428705  ../data/public/test/k/k0w00aa3iy.JPG
37961  xrp8d0pb85          901  0.499425  ../data/public/test/x/xrp8d0pb85.JPG
37962  uobnsz7na9          901  0.256282  ../data/public/test/u/uobnsz7na9.JPG
37963  4if3rbcf2d          901  0.430120  ../data/public/test/4/4if3rbcf2d.JPG

[37964 rows x 4 columns]

In [33]:
sub.drop(columns=['filepath']).to_csv('../submit/baseline_9.csv', index=False)

In [72]:
sub

id  landmark_id      conf                              filepath
0      xlf1tgh2ih          956  0.335313  ../data/public/test/x/xlf1tgh2ih.JPG
1      68a3ot4osk          956  0.302072  ../data/public/test/6/68a3ot4osk.JPG
2      si2lek4u0a          956  0.187452  ../data/public/test/s/si2lek4u0a.JPG
3      rmtqxhipnv          956  0.250135  ../data/public/test/r/rmtqxhipnv.JPG
4      2flmjdud0e          956  0.401532  ../data/public/test/2/2flmjdud0e.JPG
...           ...          ...       ...                                   ...
37959  8nlfrrdnwk          901  0.276970  ../data/public/test/8/8nlfrrdnwk.JPG
37960  k0w00aa3iy          901  0.294003  ../data/public/test/k/k0w00aa3iy.JPG
37961  xrp8d0pb85          901  0.362963  ../data/public/test/x/xrp8d0pb85.JPG
37962  uobnsz7na9          901  0.195852  ../data/public/test/u/uobnsz7na9.JPG
37963  4if3rbcf2d          901  0.282407  ../data/public/test/4/4if3rbcf2d.JPG

[37964 rows x 4 columns]

In [76]:
prior_sub = pd.read_csv('../submit/baseline_3.csv')

In [78]:
prior_sub['landmark_id']

0        956
1        956
2        956
3        956
4        956
        ... 
37959    901
37960    901
37961    901
37962    901
37963    901
Name: landmark_id, Length: 37964, dtype: int64

In [84]:
(prior_sub['landmark_id']==sub['landmark_id']).sum()

0        True
1        True
2        True
3        True
4        True
         ... 
37959    True
37960    True
37961    True
37962    True
37963    True
Name: landmark_id, Length: 37964, dtype: bool

0        956
1        956
2        956
3        956
4        956
        ... 
37959    901
37960    901
37961    901
37962    901
37963    901
Name: landmark_id, Length: 37964, dtype: int64